package com.manamaru.manmaruyoyaku.constants

class Constants {
    companion object {
        const val COLOR_PRODUCT_ID = "5ac21c4e031a6752fb806d5b"
        const val MONOCHROME_PRODUCT_ID = "5ac21cce040ab15980c9b443"
        val EMOJI_ID_PAIR = mapOf<Char,String>(
                'あ' to "001",
                'い' to "002",
                'う' to "003",
                'え' to "004",
                'お' to "005",
                'か' to "006",
                'き' to "007",
                'く' to "008",
                'け' to "009",
                'こ' to "010",
                'さ' to "011",
                'し' to "012",
                'す' to "013",
                'せ' to "014",
                'そ' to "015",
                'た' to "016",
                'ち' to "017",
                'つ' to "018",
                'て' to "019",
                'と' to "020",
                'な' to "021",
                'に' to "022",
                'ぬ' to "023",
                'ね' to "024",
                'の' to "025",
                'は' to "026",
                'ひ' to "027",
                'ふ' to "028",
                'へ' to "029",
                'ほ' to "030",
                'ま' to "031",
                'み' to "032",
                'む' to "033",
                'め' to "034",
                'も' to "035",
                'や' to "036",
                'ゆ' to "037",
                'よ' to "038",
                'ら' to "039",
                'り' to "040",
                'る' to "041",
                'れ' to "042",
                'ろ' to "043",
                'わ' to "044",
                'ん' to "046",
                'を' to "045",
                'っ' to "052",
                'ゃ' to "053",
                'ゅ' to "054",
                'ょ' to "055",
                'が' to "056",
                'ぎ' to "057",
                'ぐ' to "058",
                'げ' to "059",
                'ご' to "060",
                'ざ' to "061",
                'じ' to "062",
                'ず' to "063",
                'ぜ' to "064",
                'ぞ' to "065",
                'だ' to "066",
                'ぢ' to "067",
                'づ' to "068",
                'で' to "069",
                'ど' to "070",
                'ば' to "071",
                'び' to "072",
                'ぶ' to "073",
                'べ' to "074",
                'ぼ' to "075",
                'ぱ' to "076",
                'ぴ' to "077",
                'ぷ' to "078",
                'ぺ' to "079",
                'ぽ' to "080",)

        @JvmStatic
        fun getEmojiID(char: Char): String {
            val emojiMap = EMOJI_ID_PAIR.filterKeys { key -> char == key }
            return emojiMap.values.first()
        }
    }
}
